### PR TITLE
LPIPS modeling

### PR DESCRIPTION
**Pull request by pcuenca**
Results do not exactly match the ones from Taming Transformers, but they
look similar. More testing needed.

### CODE REVIEW

**Comment by pcuenca** [comment]
I think this should be good to go. Comparing the results between the Taming Transformers and the JAX implementations I see an error of about `2e-3` in the final result. I tested the intermediate steps (convolutional layers, `vgg` backends, normalization and spatial average) and they yield errors in the order of `1e-6` to `1e-8`. I may have missed some detail, or the final error could be caused by error accumulation, maybe?

**Comment by borisdayma** [comment]
That's clean!

We may want to port VGG to control easily partitions splitting if needed.

**Comment by pcuenca** [comment]
> We may want to port VGG to control easily partitions splitting if needed.

This PR uses the [VGG implementation in `flaxmodels`](https://github.com/matthias-wright/flaxmodels/blob/main/flaxmodels/vgg/vgg.py), which is very easy to follow. I think it will be easy to extend or adapt to our purposes whenever we need to.

**Comment by pcuenca** [comment]
Superseded by https://github.com/borisdayma/vit-vqgan/pull/1, which is proposed to become part of #6.

**Pull request closed without merging**
